# PROTOCOLS
STOP_AND_WAIT = "sw"
SELECTIVE_REPEAT = "sr"

# WINDOW SIZE
WINDOW_SIZE = 16
START_SECUENCE_NUMBER = 0
HEADER_SIZE = 8
MAX_SEGMENT_SIZE = 4096
MAX_PAYLOAD_SIZE = MAX_SEGMENT_SIZE - HEADER_SIZE
CHUNK_SIZE = MAX_PAYLOAD_SIZE * 8
TIMEOUT_SECONDS = 0.08  # 0.08
RETRANSMIT_TIMER = 0.05
NUM_FIN_SEGMENTS_TO_SEND = 3

BYTES_FILE_SIZE = 4
BYTES_FILE_NAME_SIZE = 2
BYTES_IS_UPLOAD = 1


# COLOR LOGGER
BLUE = "\033[94m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
COLOR_END = "\033[0m"
